### PR TITLE
Big Brain Bots (Massive Bot optimizations)

### PR DESCRIPTION
**Pull request by Skillz4Killz**
**Please describe the changes this PR makes and why it should be merged:**
This PR is a WIP to optimize the library for huge bots.

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Skillz4Killz** [comment]
@ayntee Hey i think this is done or almost done and would love a review when u get a chance.

**Comment by Skillz4Killz** [comment]
The last thing to do i probably to move rest and ws to a separate package

**Comment by ayntee** [comment]
Since Deno supports publication of multiple modules from a single repository, we can separate both of them into their own directory―ws and rest.

**Comment by Skillz4Killz** [comment]
@ayntee That's a good point, but tbh is it even necessary then. For example, our rest is literally just that 1 file. Deno could just pull that url directly and be done with it. Similarily for ws

**Comment by ayntee** [comment]
> @ayntee That's a good point, but tbh is it even necessary then. For example, our rest is literally just that 1 file. Deno could just pull that url directly and be done with it. Similarily for ws

I am suggesting this mainly because having separate repositories for each component is tedious.

**Comment by Skillz4Killz** [comment]
I like the way you think!

**Pull request merged**
